name: actions

on: 
  push:

jobs:

   test-actions:
        name: test action
        runs-on: ubuntu-latest
        steps: 
            - name: list files
              run: ls
            - name: checkout repo
              uses: actions/checkout@v4.2.0
            - name: list files after checkout
              run: ls       
            - name: hello-world-action
              id: hello-world-action
              uses: actions/hello-world-javascript-action@main
              with:
                who-to-greet: "Anurag"
            - name: time
              id: time
              run: echo " 'greeting time:' ${{steps.hello-world-action.outputs.time}} "
            - name : docker action
              uses: docker://hello-world:latest
   
